import type { Metadata } from "next";
import { getCurrentuser } from "@/src/features/auth.queries";
import { redirect } from "next/navigation";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await getCurrentuser();
    if(!user) return redirect("/login");
    console.log("users",user)
    if(user?.user?.role!== "employer") return redirect("/dashboard")



  return <>{children}</>
  
}
